### ISSUE TITLE
Can't Route some sources to a destination

### ISSUE THREAD

**Issue by evenover** [bitfocus/companion-module-generic-swp08#11]
I've tried to solve this, but i dont know the issue.

I have two sources that cant be routed to one destination.

Source 4 to destination 17
source 17 to destination 17

I can't seem to find the problem why it does not do it. I've almost testet all other sources at they can be routed to destination 17.

**Comment by daniep01** [comment]
Sounds like a problem in the upstream controller, could it be locked or barred? Also check the ID in the sources table is correct.

**Comment by daniep01** [comment]
@chibiconsulting - would you mind testing this on your SWP08 software, wondering if the Ultrix is doing something strange.

**Comment by chibiconsulting** [comment]
Not able to do that right now; however, it seems that DESTINATION 17 would be 10 HEX and SOURCE 4 would be 03 HEX or 10 03 if not correctly expanded. 10 03 is the DLE STX command which would require the receiver to start again in the middle of a command resulting in an invalid request. Are you expanding the DLE character prior to sending the commands?

From the protocol document:

- The data, byte count and checksum are searched for occurrence of the DLE character. When a DLE is found it is replaced with DLE DLE to prevent the data, byte count or checksum being interpreted as a command.

Also FYI, DESTINATION 17 would be 10 HEX and SOURCE 17 would be 10 HEX or 10 10, which should then be collapsed by the receiving end and also result in an invalid request due to invalid byte count.

As to why other destination 17 commands work, it could be that 10 03 is the only command that Ultrix looks for specifically.

**Comment by daniep01** [comment]
Thanks Doug. I'm sure you're right. I should read the spec more closely!

**Comment by daniep01** [comment]
I've implemented the DLE DLE modification as per the spec so this should be resolved now.
https://we.tl/t-UyvfRNLX8A

**Comment by evenover** [comment]
Tested now. I can now route source 4 and 17 to destination 17
